version: '3.8'

services:
  mcp-google-sheets:
    build: .
    container_name: mcp-google-sheets
    restart: unless-stopped
    
    environment:
      - SERVICE_ACCOUNT_PATH=/app/config/service-account.json
      - DRIVE_FOLDER_ID=${DRIVE_FOLDER_ID}
      - FASTMCP_PORT=8004
      - FASTMCP_HOST=0.0.0.0
    
    volumes:
      - ./config:/app/config:ro
    
    ports:
      - "8004:8004"
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8004/health"]
      interval: 30s
      timeout: 10s
      retries: 3
