version: "3.3"
services:
  app:
    container_name: mcp-google-sheets
    image: mcp-google-sheets
    restart: always
    build:
      context: .
    volumes: 
      - ./src:/app/src
      - ./config:/app/config:ro
    ports:
      - 172.17.0.1:8004:8004
    environment:
      DOMAIN: https://mcp-google-sheets-u51229.vm.elestio.app
      SERVICE_ACCOUNT_PATH: /app/config/service-account.json
      DRIVE_FOLDER_ID: 1mdWGHbUe0J7LzOth-b-NFPNg69P_i8ML
      FASTMCP_PORT: 8004
      FASTMCP_HOST: 0.0.0.0
    env_file:
      - .env
